logo: "YOUR LOGO TEXT"
accent: "<#02f79d>"
red: "<#ec131a>"
green: "<#46e212>"

discord: "Click here to join the discord!"
discordlink: "https://discord.gg/yourdiscord"

help:
  - ""
  - ""
  - "<gold><bold>Event Commands</bold></gold>"
  - "<gray><strikethrough>---------------------</strikethrough></gray>"
  - "<gold>/help</gold><gray> - </gray><white>Shows this page</white>"
  - "<gold>/discord</gold><gray> - </gray><white>Gives discord link</white>"
  - "<gold>/alive</gold><gray> - </gray><white>Shows you how many players are left alive</white>"






